
###
GET http://localhost:3001/report/eyeWitness

###
GET http://localhost:3001/sos/


###
POST http://localhost:3001/alluser/user
Content-Type: application/json

{
  "name": "j doe",
  "email": "jdoe@gmail.com",
  "password": "294375847589",
  "age": 90,
  "bloodType": "o+",
  "genotype": "AA",
  "nextofkinNum": "1938384849",
  "emergencyNum": "848494040",
  "knownIllnesses": ["diabetes", "hBP"],
  "state": "lagos",
  "city": "lagos",
  "lga": "kosofe",
  "residentialAdd": "some address"
}

###
GET http://localhost:3001/alluser/users

###
GET http://localhost:3001/alluser/5ec2ab509e538036a8ef7407

###
POST http://localhost:3001/incident/report
Content-Type: application/json

{
  "location": "location1",
  "description": "two keke napep jam each other",
  "reportType": "sos"
}