
POST http://localhost:3001/report
Content-Type: application/json

{
    "location": "sango",
    "description": "two keke napep jam each other",
    "reportCount": 1
}
###
GET http://localhost:3001/reports

###
POST http://localhost:3001/eyewitnessReport
Content-Type: application/json

{
    "location": "sabo",
    "description": "two keke napep jam each other",
    "reportCount": 1
}

###
POST http://localhost:3001/sos
Content-Type: application/json

{
    "location": "sabo",
    "description": "two keke napep jam each other",
    "reportCount": 1
}
